package com.covisint.papi.sample.portlet.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Consumer service. Represents a row in the &quot;Invoice_Consumer&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.covisint.papi.sample.portlet.model.impl.ConsumerModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.covisint.papi.sample.portlet.model.impl.ConsumerImpl}.
 * </p>
 *
 * @author Nitin R. Khobragade
 * @see Consumer
 * @see com.covisint.papi.sample.portlet.model.impl.ConsumerImpl
 * @see com.covisint.papi.sample.portlet.model.impl.ConsumerModelImpl
 * @generated
 */
public interface ConsumerModel extends BaseModel<Consumer> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a consumer model instance should use the {@link Consumer} interface instead.
     */

    /**
     * Returns the primary key of this consumer.
     *
     * @return the primary key of this consumer
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this consumer.
     *
     * @param primaryKey the primary key of this consumer
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the consumer ID of this consumer.
     *
     * @return the consumer ID of this consumer
     */
    public long getConsumerId();

    /**
     * Sets the consumer ID of this consumer.
     *
     * @param consumerId the consumer ID of this consumer
     */
    public void setConsumerId(long consumerId);

    /**
     * Returns the consumer name of this consumer.
     *
     * @return the consumer name of this consumer
     */
    @AutoEscape
    public String getConsumerName();

    /**
     * Sets the consumer name of this consumer.
     *
     * @param consumerName the consumer name of this consumer
     */
    public void setConsumerName(String consumerName);

    /**
     * Returns the password of this consumer.
     *
     * @return the password of this consumer
     */
    @AutoEscape
    public String getPassword();

    /**
     * Sets the password of this consumer.
     *
     * @param password the password of this consumer
     */
    public void setPassword(String password);

    public boolean isNew();

    public void setNew(boolean n);

    public boolean isCachedModel();

    public void setCachedModel(boolean cachedModel);

    public boolean isEscapedModel();

    public Serializable getPrimaryKeyObj();

    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    public ExpandoBridge getExpandoBridge();

    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    public Object clone();

    public int compareTo(Consumer consumer);

    public int hashCode();

    public CacheModel<Consumer> toCacheModel();

    public Consumer toEscapedModel();

    public Consumer toUnescapedModel();

    public String toString();

    public String toXmlString();
}
