package com.covisint.papi.sample.portlet.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Invoice service. Represents a row in the &quot;Invoice_Invoice&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.covisint.papi.sample.portlet.model.impl.InvoiceModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.covisint.papi.sample.portlet.model.impl.InvoiceImpl}.
 * </p>
 *
 * @author Nitin R. Khobragade
 * @see Invoice
 * @see com.covisint.papi.sample.portlet.model.impl.InvoiceImpl
 * @see com.covisint.papi.sample.portlet.model.impl.InvoiceModelImpl
 * @generated
 */
public interface InvoiceModel extends BaseModel<Invoice> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a invoice model instance should use the {@link Invoice} interface instead.
     */

    /**
     * Returns the primary key of this invoice.
     *
     * @return the primary key of this invoice
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this invoice.
     *
     * @param primaryKey the primary key of this invoice
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the invoice ID of this invoice.
     *
     * @return the invoice ID of this invoice
     */
    public long getInvoiceId();

    /**
     * Sets the invoice ID of this invoice.
     *
     * @param invoiceId the invoice ID of this invoice
     */
    public void setInvoiceId(long invoiceId);

    /**
     * Returns the path of this invoice.
     *
     * @return the path of this invoice
     */
    @AutoEscape
    public String getPath();

    /**
     * Sets the path of this invoice.
     *
     * @param path the path of this invoice
     */
    public void setPath(String path);

    /**
     * Returns the consumer ID of this invoice.
     *
     * @return the consumer ID of this invoice
     */
    public long getConsumerId();

    /**
     * Sets the consumer ID of this invoice.
     *
     * @param consumerId the consumer ID of this invoice
     */
    public void setConsumerId(long consumerId);

    public boolean isNew();

    public void setNew(boolean n);

    public boolean isCachedModel();

    public void setCachedModel(boolean cachedModel);

    public boolean isEscapedModel();

    public Serializable getPrimaryKeyObj();

    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    public ExpandoBridge getExpandoBridge();

    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    public Object clone();

    public int compareTo(Invoice invoice);

    public int hashCode();

    public CacheModel<Invoice> toCacheModel();

    public Invoice toEscapedModel();

    public Invoice toUnescapedModel();

    public String toString();

    public String toXmlString();
}
