package com.covisint.papi.sample.portlet.model.impl;

import com.covisint.papi.sample.portlet.model.Consumer;
import com.covisint.papi.sample.portlet.service.ConsumerLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the Consumer service. Represents a row in the &quot;Invoice_Consumer&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ConsumerImpl}.
 * </p>
 *
 * @author Nitin R. Khobragade
 * @see ConsumerImpl
 * @see com.covisint.papi.sample.portlet.model.Consumer
 * @generated
 */
public abstract class ConsumerBaseImpl extends ConsumerModelImpl
    implements Consumer {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a consumer model instance should use the {@link Consumer} interface instead.
     */
    public void persist() throws SystemException {
        if (this.isNew()) {
            ConsumerLocalServiceUtil.addConsumer(this);
        } else {
            ConsumerLocalServiceUtil.updateConsumer(this);
        }
    }
}
