package com.covisint.papi.sample.portlet.service.base;

import com.covisint.papi.sample.portlet.model.Invoice;
import com.covisint.papi.sample.portlet.service.ConsumerLocalService;
import com.covisint.papi.sample.portlet.service.ConsumerService;
import com.covisint.papi.sample.portlet.service.InvoiceLocalService;
import com.covisint.papi.sample.portlet.service.InvoiceService;
import com.covisint.papi.sample.portlet.service.persistence.ConsumerPersistence;
import com.covisint.papi.sample.portlet.service.persistence.InvoicePersistence;

import com.liferay.counter.service.CounterLocalService;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.model.PersistedModel;
import com.liferay.portal.service.BaseLocalServiceImpl;
import com.liferay.portal.service.PersistedModelLocalServiceRegistryUtil;
import com.liferay.portal.service.ResourceLocalService;
import com.liferay.portal.service.ResourceService;
import com.liferay.portal.service.UserLocalService;
import com.liferay.portal.service.UserService;
import com.liferay.portal.service.persistence.ResourcePersistence;
import com.liferay.portal.service.persistence.UserPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * The base implementation of the invoice local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.covisint.papi.sample.portlet.service.impl.InvoiceLocalServiceImpl}.
 * </p>
 *
 * @author Nitin R. Khobragade
 * @see com.covisint.papi.sample.portlet.service.impl.InvoiceLocalServiceImpl
 * @see com.covisint.papi.sample.portlet.service.InvoiceLocalServiceUtil
 * @generated
 */
public abstract class InvoiceLocalServiceBaseImpl extends BaseLocalServiceImpl
    implements InvoiceLocalService, IdentifiableBean {
    @BeanReference(type = ConsumerLocalService.class)
    protected ConsumerLocalService consumerLocalService;
    @BeanReference(type = ConsumerService.class)
    protected ConsumerService consumerService;
    @BeanReference(type = ConsumerPersistence.class)
    protected ConsumerPersistence consumerPersistence;
    @BeanReference(type = InvoiceLocalService.class)
    protected InvoiceLocalService invoiceLocalService;
    @BeanReference(type = InvoiceService.class)
    protected InvoiceService invoiceService;
    @BeanReference(type = InvoicePersistence.class)
    protected InvoicePersistence invoicePersistence;
    @BeanReference(type = CounterLocalService.class)
    protected CounterLocalService counterLocalService;
    @BeanReference(type = ResourceLocalService.class)
    protected ResourceLocalService resourceLocalService;
    @BeanReference(type = ResourceService.class)
    protected ResourceService resourceService;
    @BeanReference(type = ResourcePersistence.class)
    protected ResourcePersistence resourcePersistence;
    @BeanReference(type = UserLocalService.class)
    protected UserLocalService userLocalService;
    @BeanReference(type = UserService.class)
    protected UserService userService;
    @BeanReference(type = UserPersistence.class)
    protected UserPersistence userPersistence;
    private String _beanIdentifier;
    private ClassLoader _classLoader;
    private InvoiceLocalServiceClpInvoker _clpInvoker = new InvoiceLocalServiceClpInvoker();

    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. Always use {@link com.covisint.papi.sample.portlet.service.InvoiceLocalServiceUtil} to access the invoice local service.
     */

    /**
     * Adds the invoice to the database. Also notifies the appropriate model listeners.
     *
     * @param invoice the invoice
     * @return the invoice that was added
     * @throws SystemException if a system exception occurred
     */
    @Indexable(type = IndexableType.REINDEX)
    public Invoice addInvoice(Invoice invoice) throws SystemException {
        invoice.setNew(true);

        return invoicePersistence.update(invoice, false);
    }

    /**
     * Creates a new invoice with the primary key. Does not add the invoice to the database.
     *
     * @param invoiceId the primary key for the new invoice
     * @return the new invoice
     */
    public Invoice createInvoice(long invoiceId) {
        return invoicePersistence.create(invoiceId);
    }

    /**
     * Deletes the invoice with the primary key from the database. Also notifies the appropriate model listeners.
     *
     * @param invoiceId the primary key of the invoice
     * @return the invoice that was removed
     * @throws PortalException if a invoice with the primary key could not be found
     * @throws SystemException if a system exception occurred
     */
    @Indexable(type = IndexableType.DELETE)
    public Invoice deleteInvoice(long invoiceId)
        throws PortalException, SystemException {
        return invoicePersistence.remove(invoiceId);
    }

    /**
     * Deletes the invoice from the database. Also notifies the appropriate model listeners.
     *
     * @param invoice the invoice
     * @return the invoice that was removed
     * @throws SystemException if a system exception occurred
     */
    @Indexable(type = IndexableType.DELETE)
    public Invoice deleteInvoice(Invoice invoice) throws SystemException {
        return invoicePersistence.remove(invoice);
    }

    public DynamicQuery dynamicQuery() {
        Class<?> clazz = getClass();

        return DynamicQueryFactoryUtil.forClass(Invoice.class,
            clazz.getClassLoader());
    }

    /**
     * Performs a dynamic query on the database and returns the matching rows.
     *
     * @param dynamicQuery the dynamic query
     * @return the matching rows
     * @throws SystemException if a system exception occurred
     */
    @SuppressWarnings("rawtypes")
    public List dynamicQuery(DynamicQuery dynamicQuery)
        throws SystemException {
        return invoicePersistence.findWithDynamicQuery(dynamicQuery);
    }

    /**
     * Performs a dynamic query on the database and returns a range of the matching rows.
     *
     * <p>
     * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
     * </p>
     *
     * @param dynamicQuery the dynamic query
     * @param start the lower bound of the range of model instances
     * @param end the upper bound of the range of model instances (not inclusive)
     * @return the range of matching rows
     * @throws SystemException if a system exception occurred
     */
    @SuppressWarnings("rawtypes")
    public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end)
        throws SystemException {
        return invoicePersistence.findWithDynamicQuery(dynamicQuery, start, end);
    }

    /**
     * Performs a dynamic query on the database and returns an ordered range of the matching rows.
     *
     * <p>
     * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
     * </p>
     *
     * @param dynamicQuery the dynamic query
     * @param start the lower bound of the range of model instances
     * @param end the upper bound of the range of model instances (not inclusive)
     * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
     * @return the ordered range of matching rows
     * @throws SystemException if a system exception occurred
     */
    @SuppressWarnings("rawtypes")
    public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end,
        OrderByComparator orderByComparator) throws SystemException {
        return invoicePersistence.findWithDynamicQuery(dynamicQuery, start,
            end, orderByComparator);
    }

    /**
     * Returns the number of rows that match the dynamic query.
     *
     * @param dynamicQuery the dynamic query
     * @return the number of rows that match the dynamic query
     * @throws SystemException if a system exception occurred
     */
    public long dynamicQueryCount(DynamicQuery dynamicQuery)
        throws SystemException {
        return invoicePersistence.countWithDynamicQuery(dynamicQuery);
    }

    public Invoice fetchInvoice(long invoiceId) throws SystemException {
        return invoicePersistence.fetchByPrimaryKey(invoiceId);
    }

    /**
     * Returns the invoice with the primary key.
     *
     * @param invoiceId the primary key of the invoice
     * @return the invoice
     * @throws PortalException if a invoice with the primary key could not be found
     * @throws SystemException if a system exception occurred
     */
    public Invoice getInvoice(long invoiceId)
        throws PortalException, SystemException {
        return invoicePersistence.findByPrimaryKey(invoiceId);
    }

    public PersistedModel getPersistedModel(Serializable primaryKeyObj)
        throws PortalException, SystemException {
        return invoicePersistence.findByPrimaryKey(primaryKeyObj);
    }

    /**
     * Returns a range of all the invoices.
     *
     * <p>
     * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
     * </p>
     *
     * @param start the lower bound of the range of invoices
     * @param end the upper bound of the range of invoices (not inclusive)
     * @return the range of invoices
     * @throws SystemException if a system exception occurred
     */
    public List<Invoice> getInvoices(int start, int end)
        throws SystemException {
        return invoicePersistence.findAll(start, end);
    }

    /**
     * Returns the number of invoices.
     *
     * @return the number of invoices
     * @throws SystemException if a system exception occurred
     */
    public int getInvoicesCount() throws SystemException {
        return invoicePersistence.countAll();
    }

    /**
     * Updates the invoice in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
     *
     * @param invoice the invoice
     * @return the invoice that was updated
     * @throws SystemException if a system exception occurred
     */
    @Indexable(type = IndexableType.REINDEX)
    public Invoice updateInvoice(Invoice invoice) throws SystemException {
        return updateInvoice(invoice, true);
    }

    /**
     * Updates the invoice in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
     *
     * @param invoice the invoice
     * @param merge whether to merge the invoice with the current session. See {@link com.liferay.portal.service.persistence.BatchSession#update(com.liferay.portal.kernel.dao.orm.Session, com.liferay.portal.model.BaseModel, boolean)} for an explanation.
     * @return the invoice that was updated
     * @throws SystemException if a system exception occurred
     */
    @Indexable(type = IndexableType.REINDEX)
    public Invoice updateInvoice(Invoice invoice, boolean merge)
        throws SystemException {
        invoice.setNew(false);

        return invoicePersistence.update(invoice, merge);
    }

    /**
     * Returns the consumer local service.
     *
     * @return the consumer local service
     */
    public ConsumerLocalService getConsumerLocalService() {
        return consumerLocalService;
    }

    /**
     * Sets the consumer local service.
     *
     * @param consumerLocalService the consumer local service
     */
    public void setConsumerLocalService(
        ConsumerLocalService consumerLocalService) {
        this.consumerLocalService = consumerLocalService;
    }

    /**
     * Returns the consumer remote service.
     *
     * @return the consumer remote service
     */
    public ConsumerService getConsumerService() {
        return consumerService;
    }

    /**
     * Sets the consumer remote service.
     *
     * @param consumerService the consumer remote service
     */
    public void setConsumerService(ConsumerService consumerService) {
        this.consumerService = consumerService;
    }

    /**
     * Returns the consumer persistence.
     *
     * @return the consumer persistence
     */
    public ConsumerPersistence getConsumerPersistence() {
        return consumerPersistence;
    }

    /**
     * Sets the consumer persistence.
     *
     * @param consumerPersistence the consumer persistence
     */
    public void setConsumerPersistence(ConsumerPersistence consumerPersistence) {
        this.consumerPersistence = consumerPersistence;
    }

    /**
     * Returns the invoice local service.
     *
     * @return the invoice local service
     */
    public InvoiceLocalService getInvoiceLocalService() {
        return invoiceLocalService;
    }

    /**
     * Sets the invoice local service.
     *
     * @param invoiceLocalService the invoice local service
     */
    public void setInvoiceLocalService(InvoiceLocalService invoiceLocalService) {
        this.invoiceLocalService = invoiceLocalService;
    }

    /**
     * Returns the invoice remote service.
     *
     * @return the invoice remote service
     */
    public InvoiceService getInvoiceService() {
        return invoiceService;
    }

    /**
     * Sets the invoice remote service.
     *
     * @param invoiceService the invoice remote service
     */
    public void setInvoiceService(InvoiceService invoiceService) {
        this.invoiceService = invoiceService;
    }

    /**
     * Returns the invoice persistence.
     *
     * @return the invoice persistence
     */
    public InvoicePersistence getInvoicePersistence() {
        return invoicePersistence;
    }

    /**
     * Sets the invoice persistence.
     *
     * @param invoicePersistence the invoice persistence
     */
    public void setInvoicePersistence(InvoicePersistence invoicePersistence) {
        this.invoicePersistence = invoicePersistence;
    }

    /**
     * Returns the counter local service.
     *
     * @return the counter local service
     */
    public CounterLocalService getCounterLocalService() {
        return counterLocalService;
    }

    /**
     * Sets the counter local service.
     *
     * @param counterLocalService the counter local service
     */
    public void setCounterLocalService(CounterLocalService counterLocalService) {
        this.counterLocalService = counterLocalService;
    }

    /**
     * Returns the resource local service.
     *
     * @return the resource local service
     */
    public ResourceLocalService getResourceLocalService() {
        return resourceLocalService;
    }

    /**
     * Sets the resource local service.
     *
     * @param resourceLocalService the resource local service
     */
    public void setResourceLocalService(
        ResourceLocalService resourceLocalService) {
        this.resourceLocalService = resourceLocalService;
    }

    /**
     * Returns the resource remote service.
     *
     * @return the resource remote service
     */
    public ResourceService getResourceService() {
        return resourceService;
    }

    /**
     * Sets the resource remote service.
     *
     * @param resourceService the resource remote service
     */
    public void setResourceService(ResourceService resourceService) {
        this.resourceService = resourceService;
    }

    /**
     * Returns the resource persistence.
     *
     * @return the resource persistence
     */
    public ResourcePersistence getResourcePersistence() {
        return resourcePersistence;
    }

    /**
     * Sets the resource persistence.
     *
     * @param resourcePersistence the resource persistence
     */
    public void setResourcePersistence(ResourcePersistence resourcePersistence) {
        this.resourcePersistence = resourcePersistence;
    }

    /**
     * Returns the user local service.
     *
     * @return the user local service
     */
    public UserLocalService getUserLocalService() {
        return userLocalService;
    }

    /**
     * Sets the user local service.
     *
     * @param userLocalService the user local service
     */
    public void setUserLocalService(UserLocalService userLocalService) {
        this.userLocalService = userLocalService;
    }

    /**
     * Returns the user remote service.
     *
     * @return the user remote service
     */
    public UserService getUserService() {
        return userService;
    }

    /**
     * Sets the user remote service.
     *
     * @param userService the user remote service
     */
    public void setUserService(UserService userService) {
        this.userService = userService;
    }

    /**
     * Returns the user persistence.
     *
     * @return the user persistence
     */
    public UserPersistence getUserPersistence() {
        return userPersistence;
    }

    /**
     * Sets the user persistence.
     *
     * @param userPersistence the user persistence
     */
    public void setUserPersistence(UserPersistence userPersistence) {
        this.userPersistence = userPersistence;
    }

    public void afterPropertiesSet() {
        Class<?> clazz = getClass();

        _classLoader = clazz.getClassLoader();

        PersistedModelLocalServiceRegistryUtil.register("com.covisint.papi.sample.portlet.model.Invoice",
            invoiceLocalService);
    }

    public void destroy() {
        PersistedModelLocalServiceRegistryUtil.unregister(
            "com.covisint.papi.sample.portlet.model.Invoice");
    }

    /**
     * Returns the Spring bean ID for this bean.
     *
     * @return the Spring bean ID for this bean
     */
    public String getBeanIdentifier() {
        return _beanIdentifier;
    }

    /**
     * Sets the Spring bean ID for this bean.
     *
     * @param beanIdentifier the Spring bean ID for this bean
     */
    public void setBeanIdentifier(String beanIdentifier) {
        _beanIdentifier = beanIdentifier;
    }

    public Object invokeMethod(String name, String[] parameterTypes,
        Object[] arguments) throws Throwable {
        Thread currentThread = Thread.currentThread();

        ClassLoader contextClassLoader = currentThread.getContextClassLoader();

        if (contextClassLoader != _classLoader) {
            currentThread.setContextClassLoader(_classLoader);
        }

        try {
            return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
        } finally {
            if (contextClassLoader != _classLoader) {
                currentThread.setContextClassLoader(contextClassLoader);
            }
        }
    }

    protected Class<?> getModelClass() {
        return Invoice.class;
    }

    protected String getModelClassName() {
        return Invoice.class.getName();
    }

    /**
     * Performs an SQL query.
     *
     * @param sql the sql query
     */
    protected void runSQL(String sql) throws SystemException {
        try {
            DataSource dataSource = invoicePersistence.getDataSource();

            SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
                    sql, new int[0]);

            sqlUpdate.update();
        } catch (Exception e) {
            throw new SystemException(e);
        }
    }
}
